# Generated by Django 3.0.4 on 2022-11-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_detailed_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='pessanger_detail',
            fields=[
                ('Trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('Trip_same_id', models.IntegerField(default=1)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('age', models.IntegerField(default=10)),
                ('username', models.CharField(max_length=10)),
                ('Trip_date', models.DateField()),
                ('payment', models.IntegerField(default=50)),
                ('city', models.CharField(max_length=20)),
                ('pay_done', models.IntegerField(default=0)),
            ],
        ),
    ]
