# Generated by Django 3.0.4 on 2022-11-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetBanking',
            fields=[
                ('Username', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=14)),
                ('Bank', models.CharField(max_length=25)),
                ('Balance', models.CharField(max_length=9)),
            ],
        ),
    ]
