# Generated by Django 3.0.4 on 2022-11-01 15:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0006_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2022, 11, 1, 15, 12, 59, 323082, tzinfo=utc), max_length=19),
        ),
    ]
