# Generated by Django 3.0.4 on 2022-12-13 14:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0018_auto_20221213_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='type_place',
            field=models.CharField(default='TN', max_length=5),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2022, 12, 13, 14, 55, 1, 257817, tzinfo=utc), max_length=19),
        ),
    ]
