# Generated by Django 3.0.4 on 2022-12-14 22:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0019_auto_20221213_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='close_time',
            field=models.CharField(default='18:00', max_length=10),
        ),
        migrations.AddField(
            model_name='places',
            name='email',
            field=models.EmailField(default='thanhchau2279@gmail.com', max_length=50),
        ),
        migrations.AddField(
            model_name='places',
            name='open_time',
            field=models.CharField(default='7:00', max_length=10),
        ),
        migrations.AddField(
            model_name='places',
            name='phone',
            field=models.IntegerField(default='0917725514', max_length=12),
        ),
        migrations.AddField(
            model_name='places',
            name='place_map',
            field=models.CharField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3837.1550019355527!2d108.33532111418964!3d15.900948448150865!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31420de155207241%3A0xb084a84384f41fbf!2zTMOgbmcgUmF1IFRyw6AgUXXhur8!5e0!3m2!1svi!2s!4v1671057337843!5m2!1svi!2s', max_length=300),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2022, 12, 14, 22, 42, 32, 916586, tzinfo=utc), max_length=19),
        ),
    ]
