# Generated by Django 3.0.4 on 2022-12-14 23:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0020_auto_20221215_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='place_name_short',
            field=models.CharField(default='culaocham', max_length=100),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2022, 12, 14, 23, 36, 52, 694945, tzinfo=utc), max_length=19),
        ),
    ]
