# Generated by Django 3.0.4 on 2022-12-15 15:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0021_auto_20221215_0636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel_types',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('code_name', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.AlterField(
            model_name='places',
            name='phone',
            field=models.IntegerField(default='0917725514'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2022, 12, 15, 15, 27, 20, 269551, tzinfo=utc), max_length=19),
        ),
    ]
