# Generated by Django 3.0.4 on 2022-12-16 02:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0024_auto_20221216_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='type_place',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2022, 12, 16, 2, 44, 10, 632806, tzinfo=utc), max_length=19),
        ),
    ]
