# Generated by Django 3.0.4 on 2022-12-16 02:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0026_auto_20221216_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='type_place',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2022, 12, 16, 2, 49, 52, 750403, tzinfo=utc), max_length=19),
        ),
    ]
