# Generated by Django 3.0.4 on 2022-12-16 02:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0027_auto_20221216_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='type_place',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2022, 12, 16, 2, 51, 29, 592299, tzinfo=utc), max_length=19),
        ),
    ]
