# Generated by Django 3.0.4 on 2022-12-26 16:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0028_auto_20221216_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('spec_id', models.AutoField(primary_key=True, serialize=False)),
                ('img1', models.ImageField(upload_to='pics')),
                ('img2', models.ImageField(upload_to='pics')),
                ('img3', models.ImageField(upload_to='pics')),
                ('type_spec', models.IntegerField(default=1)),
                ('desc1', models.TextField()),
                ('desc2', models.TextField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Specialties_types',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2022, 12, 26, 16, 14, 30, 165319, tzinfo=utc), max_length=19),
        ),
    ]
