# Generated by Django 3.0.4 on 2023-01-01 18:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0029_auto_20221226_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialties',
            name='spec_name',
            field=models.CharField(default='Mỳ Quảng', max_length=100),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2023, 1, 1, 18, 52, 28, 541825, tzinfo=utc), max_length=19),
        ),
    ]
