# Generated by Django 3.0.4 on 2023-01-05 15:11

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0030_auto_20230102_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myrating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=1)),
                ('tour_id', models.IntegerField(default=1)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2023, 1, 5, 15, 10, 59, 390878, tzinfo=utc), max_length=19),
        ),
    ]
