# Generated by Django 3.0.4 on 2023-01-06 05:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0032_auto_20230106_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylist',
            name='user',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2023, 1, 6, 5, 24, 52, 809187, tzinfo=utc), max_length=19),
        ),
    ]
