# Generated by Django 3.0.4 on 2023-01-06 06:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0034_auto_20230106_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2023, 1, 6, 6, 12, 3, 625687, tzinfo=utc), max_length=19),
        ),
    ]
