# Generated by Django 3.0.4 on 2023-01-06 06:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0035_auto_20230106_1312'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myrating',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2023, 1, 6, 6, 14, 28, 785837, tzinfo=utc), max_length=19),
        ),
    ]
