# Generated by Django 3.0.4 on 2023-01-06 06:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0037_auto_20230106_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myrating',
            old_name='tour_id',
            new_name='tour',
        ),
        migrations.RenameField(
            model_name='myrating',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2023, 1, 6, 6, 18, 46, 590767, tzinfo=utc), max_length=19),
        ),
    ]
