# Generated by Django 3.0.4 on 2023-01-06 15:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0038_auto_20230106_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrating',
            name='comment',
            field=models.CharField(default='Good!!!', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2023, 1, 6, 15, 51, 55, 926238, tzinfo=utc), max_length=19),
        ),
    ]
