# Generated by Django 3.0.4 on 2023-01-09 16:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0039_auto_20230106_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailed_desc',
            name='num_bookings',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2023, 1, 9, 16, 4, 38, 447058, tzinfo=utc), max_length=19),
        ),
    ]
