# Generated by Django 3.0.4 on 2023-01-11 02:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0040_auto_20230109_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrating',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2023, 1, 11, 2, 59, 42, 475001, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2023, 1, 11, 2, 59, 42, 475001, tzinfo=utc), max_length=19),
        ),
    ]
