# Generated by Django 3.0.4 on 2023-01-11 03:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0041_auto_20230111_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myrating',
            name='date_time',
        ),
        migrations.AddField(
            model_name='myrating',
            name='time_rate',
            field=models.DateField(default=datetime.datetime(2023, 1, 11, 3, 0, 2, 881635, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2023, 1, 11, 3, 0, 2, 881635, tzinfo=utc), max_length=19),
        ),
    ]
