# Generated by Django 3.0.4 on 2023-01-11 15:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0043_auto_20230111_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrating',
            name='time_rate',
            field=models.DateField(default=datetime.datetime(2023, 1, 11, 15, 21, 26, 245114, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='placerating',
            name='comment',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2023, 1, 11, 15, 21, 26, 239128, tzinfo=utc), max_length=19),
        ),
    ]
