# Generated by Django 3.0.4 on 2023-01-11 16:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0045_auto_20230111_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailed_desc',
            name='rating',
            field=models.CharField(default='5', max_length=10),
        ),
        migrations.AlterField(
            model_name='myrating',
            name='time_rate',
            field=models.DateField(default=datetime.datetime(2023, 1, 11, 16, 53, 13, 417570, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2023, 1, 11, 16, 53, 13, 417570, tzinfo=utc), max_length=19),
        ),
    ]
