# Generated by Django 3.0.4 on 2023-01-12 13:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0046_auto_20230111_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrating',
            name='time_rate',
            field=models.DateField(default=datetime.datetime(2023, 1, 12, 13, 7, 46, 57404, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2023, 1, 12, 13, 7, 46, 41781, tzinfo=utc), max_length=19),
        ),
    ]
