# Generated by Django 3.0.4 on 2023-01-12 13:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0049_auto_20230112_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailed_desc',
            name='trip_date',
            field=models.CharField(default='2022-01-30', max_length=19),
        ),
        migrations.AlterField(
            model_name='myrating',
            name='time_rate',
            field=models.DateField(default=datetime.datetime(2023, 1, 12, 13, 44, 32, 249071, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2023, 1, 12, 13, 44, 32, 249071, tzinfo=utc), max_length=19),
        ),
    ]
