from django.contrib import admin
from django.urls import path, include

from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('admin-home/', include('traveladmin.urls')),
    path('dj-admin/', admin.site.urls),
    path('get/', views.get_bot_response, name='get_bot_response'),
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('all-user', views.all_users, name='all-user'),
    path('logout', views.logout, name='logout'),
    path('search', views.search, name='search'),
    path('blog', views.blog, name='blog'),
    path('specialties', views.specialties, name='specialties'),
    path('about', views.about, name='about'),
    path('places', views.places, name='places'),
    path('recommend-places', views.recommend, name='recommend-places'),
    path('check-places-vh', views.check_places_VH, name='check-places-vh'),
    path('check-places-tn', views.check_places_TN, name='check-places-tn'),
    path('check-places-lq', views.check_places_LQ, name='check-places-lq'),
    path('check-places-nn', views.check_places_NN, name='check-places-nn'),
    path('places/<int:place_id>', views.place_details, name='places-details'),
    path('specialties/<int:spec_id>', views.specialties_details, name='specialties-details'),
    path('filter-places', views.filter_places, name='filter_places'),
    path('filter-specialties', views.filter_specialties, name='filter_specialties'),
    path('load-more-tours', views.load_more_tours, name='load-more-tours'),
    path('load-more-private-tours', views.load_more_private_tours, name='load-more-private-tours'),
    path('destination_list/<str:city_name>', views.destination_list, name='destination_list'),
    path('destination_list/destination_details/<int:tour_id>', views.destination_details, name='destination_details'),
    path('destination_details/<int:tour_id>', views.destination_details, name='destination_details'),
    path('destination_details/pessanger_detail_def/<str:city_name>',views.pessanger_detail_def,name='pessanger_detail_def'),
    path('destination_list/destination_details/pessanger_detail_def/<str:city_name>',views.pessanger_detail_def,name='pessanger_detail_def'),
    path('upcoming_trips', views.upcoming_trips, name='upcoming_trips'),
    path('destination_details/pessanger_detail_def/pessanger_detail_def/card_payment', views.card_payment, name='card_payment'),
    path('destination_list/destination_details/pessanger_detail_def/pessanger_detail_def/card_payment', views.card_payment, name='card_payment'),
    path('destination_details/pessanger_detail_def/pessanger_detail_def/otp_verification', views.otp_verification, name='otp_verification'),
    path('destination_list/destination_details/pessanger_detail_def/pessanger_detail_def/otp_verification', views.otp_verification, name='otp_verification'),
    path('destination_details/pessanger_detail_def/pessanger_detail_def/net_payment', views.net_payment, name='net_payment'),
    path('destination_list/destination_details/pessanger_detail_def/pessanger_detail_def/net_payment', views.net_payment, name='net_payment'),
    path('tours-list', views.tours_list, name='tours-list'),
    path('filter-tours', views.filter_tours, name='filter_tours'),
    path('user/<int:user_id>',views.user, name='user'),

]
