from django.contrib import admin
from django.urls import path, include

from . import views
urlpatterns = [
    path('', views.admin_login, name='admin-login'),
    path('logout-admin', views.logout_admin, name='logout-admin'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('destination', views.destination, name='destination'),
    path('add-destination', views.add_destination, name='add-destination'),
    path('edit-destination', views.edit_destination, name='edit-destination'),
    path('update-destination/<str:id>', views.update_destination, name='update-destination'),
    path('delete-destination/<str:id>', views.delete_destination, name='delete-destination'),
    path('destination-details', views.destination_details, name='destination-details'),
    path('add-destination-details', views.add_destination_details, name='add-destination-details'),
    path('edit-destination-details', views.edit_destination_details, name='edit-destination-details'),
    path('update-destination-details/<str:id>', views.update_destination_details, name='update-destination-details'),
    path('delete-destination-details/<str:id>', views.delete_destination_details, name='delete-destination-details'),
    path('users', views.users, name='users'),
    path('edit-users', views.edit_users, name= 'edit-users'),
    path('delete-users/<str:id>', views.delete_users, name='delete-users'),
    path('places-list', views.places_list, name='places-list'),
    path('add-place', views.add_place, name='add-place'),
    path('edit-place', views.edit_place, name='edit-place'),
    path('update-place/<str:id>', views.update_place, name='update-place'),
    path('delete-place/<str:id>', views.delete_place, name='delete-place'),
    path('foods-list', views.foods_list, name='foods-list'),
    path('add-food', views.add_food, name='add-food'),
    path('edit-food', views.edit_food, name='edit-food'),
    path('update-food/<str:id>', views.update_food, name='update-food'),
    path('delete-food/<str:id>', views.delete_food, name='delete-food'),
    path('bookings', views.bookings, name='bookings'),
    path('delete-book/<str:id>', views.delete_book, name='delete-book'),
    path('type-places', views.type_places, name='type-places'),
    path('add-type-place', views.add_type_place, name='add-type-place'),
    path('edit-type-place', views.edit_type_place, name='edit-type-place'),
    path('update-type-place/<str:id>', views.update_type_place, name='update-type-place'),
    path('delete-type-place/<str:id>', views.delete_type_place, name='delete-type-place'),
    path('type-foods-business', views.type_foods_business, name='type-foods-business'),
    path('add-type-food-business', views.add_type_food_business, name='add-type-food-business'),
    path('edit-type-food-business', views.edit_type_food_business, name='edit-type-food-business'),
    path('update-type-food-business/<str:id>', views.update_type_food_business, name='update-type-food-business'),
    path('delete-type-food-business/<str:id>', views.delete_type_food_business, name='delete-type-food-business')
]